name : pull to check the code 

on:
  pull_request:
    branches:
      - main

 
jobs:
  check-code:
    name: Check code from repo
    runs-on: ubuntu-latest

    steps:
    - name: Fetch code from repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and Run Docker Compose
      run: |
        docker-compose up -d --build
        docker-compose run test
        
